export type Kind = "EXPENSE" | "INCOME" | "TRANSFER";

export interface DefaultCategory {
  /** Original name; stored as the category's systemKey so users can rename it safely. */
  name: string;
  kind: Kind;
  color: string; // palette token, see lib/palette.ts
  icon: string; // lucide icon name, see components/category-icon.tsx
  description: string; // given to the AI categorizer
}

/**
 * Bump when DEFAULT_CATEGORIES or SYSTEM_RULES change. Existing users are upgraded on their next
 * page load (services/user.ts): missing categories are added, the built-in lexicon is re-synced,
 * and rules are re-applied to non-manual history.
 */
export const DEFAULTS_VERSION = 2;

/** systemKeys referenced by code. These categories can be renamed but never deleted. */
export const FALLBACK_EXPENSE = "Miscellaneous";
export const FALLBACK_INCOME = "Other Income";
export const TRANSFER_CATEGORY = "Transfers";
export const PROTECTED_SYSTEM_KEYS = new Set([FALLBACK_EXPENSE, FALLBACK_INCOME, TRANSFER_CATEGORY]);

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  {
    name: "Groceries",
    kind: "EXPENSE",
    color: "sage",
    icon: "ShoppingBasket",
    description: "Supermarkets, mini-markets, organic stores, frozen food, food markets",
  },
  {
    name: "Dining Out",
    kind: "EXPENSE",
    color: "terracotta",
    icon: "UtensilsCrossed",
    description: "Meals at restaurants, fast food, takeaway and food delivery (Uber Eats, Deliveroo). Not bars, drinks or quick coffees.",
  },
  {
    name: "Bars & Nightlife",
    kind: "EXPENSE",
    color: "wine",
    icon: "Beer",
    description: "Bars, pubs, terrace drinks, apéro, beers, cocktails, sharing boards (planches), clubs and nights out",
  },
  {
    name: "Coffee & Snacks",
    kind: "EXPENSE",
    color: "espresso",
    icon: "Coffee",
    description: "Coffee shops, a coffee at a café counter or terrace, vending machines (Maxicoffee, Selecta, Nayax), bakeries and quick snacks",
  },
  {
    name: "Canteen",
    kind: "EXPENSE",
    color: "honey",
    icon: "Soup",
    description: "School or company canteen and cafeteria: meals and meal-card top-ups (company restaurant, CROUS, Izly, Sodexo, Elior)",
  },
  {
    name: "Transport",
    kind: "EXPENSE",
    color: "slate",
    icon: "TramFront",
    description: "Public transit, Navigo, ride hailing, taxis, bike and scooter rentals (Vélib, Lime, Dott), fuel, parking, tolls",
  },
  { name: "Housing", kind: "EXPENSE", color: "stone", icon: "House", description: "Rent, mortgage payments, property fees, home maintenance" },
  { name: "Utilities", kind: "EXPENSE", color: "steel", icon: "Plug", description: "Electricity, gas, water, internet, mobile phone plans" },
  {
    name: "Subscriptions",
    kind: "EXPENSE",
    color: "lavender",
    icon: "Repeat",
    description: "Streaming, music, software, apps and in-app purchases (Apple, Google), cloud storage, memberships",
  },
  { name: "Shopping", kind: "EXPENSE", color: "rose", icon: "ShoppingBag", description: "Clothing, electronics, online stores and marketplaces, home goods" },
  { name: "Health", kind: "EXPENSE", color: "mint", icon: "HeartPulse", description: "Pharmacy, doctors, dentists, opticians, mutuelle co-pays" },
  { name: "Entertainment", kind: "EXPENSE", color: "plum", icon: "Ticket", description: "Cinema, concerts, events, races, museums, games, hobbies" },
  { name: "Travel", kind: "EXPENSE", color: "ocean", icon: "Plane", description: "Train tickets (SNCF), flights, hotels, holiday rentals" },
  { name: "Education", kind: "EXPENSE", color: "ochre", icon: "GraduationCap", description: "Tuition, school fees, courses, books, school supplies" },
  { name: "Personal Care", kind: "EXPENSE", color: "blush", icon: "Sparkles", description: "Hairdresser, beauty, gym, wellness" },
  { name: "Insurance", kind: "EXPENSE", color: "fog", icon: "ShieldCheck", description: "Home, car, health, life insurance premiums (usually direct debits)" },
  { name: "Taxes", kind: "EXPENSE", color: "graphite", icon: "Landmark", description: "Income tax, property tax, government fees" },
  { name: "Fees & Charges", kind: "EXPENSE", color: "clay", icon: "Receipt", description: "Bank account and card fees, overdraft charges, FX fees" },
  { name: "Cash", kind: "EXPENSE", color: "sand", icon: "Banknote", description: "ATM withdrawals" },
  { name: "Gifts & Donations", kind: "EXPENSE", color: "coral", icon: "Gift", description: "Gifts, charity, donations, prize pools (cagnottes)" },
  { name: "Kids & Family", kind: "EXPENSE", color: "peach", icon: "Baby", description: "Childcare, school activities, family expenses" },
  { name: "Pets", kind: "EXPENSE", color: "moss", icon: "PawPrint", description: "Vet, pet food, pet supplies" },
  { name: FALLBACK_EXPENSE, kind: "EXPENSE", color: "ash", icon: "CircleDashed", description: "Expenses that fit no other category" },
  {
    name: "Salary",
    kind: "INCOME",
    color: "emerald",
    icon: "BriefcaseBusiness",
    description: "Wages, payroll, apprenticeship pay, internship stipends, bonuses",
  },
  { name: "Refunds", kind: "INCOME", color: "teal", icon: "Undo2", description: "Merchant refunds, reimbursements (CPAM, mutuelle, employer expenses)" },
  { name: "Investment Income", kind: "INCOME", color: "jade", icon: "TrendingUp", description: "Interest (livret), dividends, capital gains" },
  { name: FALLBACK_INCOME, kind: "INCOME", color: "seafoam", icon: "Coins", description: "Any other incoming money" },
  {
    name: TRANSFER_CATEGORY,
    kind: "TRANSFER",
    color: "mist",
    icon: "ArrowLeftRight",
    description: "Moves between the user's own accounts (e.g. Crédit Agricole ↔ Revolut), top-ups, currency exchanges",
  },
  {
    name: "Savings & Investments",
    kind: "TRANSFER",
    color: "indigo",
    icon: "PiggyBank",
    description: "Transfers into savings (Livret A, LDDS), brokerage, crypto, pension accounts",
  },
];

export interface SystemRule {
  pattern: string;
  category: string; // systemKey of the target category
  direction?: "DEBIT" | "CREDIT";
  /** CONTAINS (default) matches at a word start; REGEX for patterns that need more precision. */
  matchType?: "CONTAINS" | "REGEX";
}

const contains = (category: string, direction: SystemRule["direction"], patterns: string[]): SystemRule[] =>
  patterns.map((pattern) => ({ pattern, category, direction }));

/** Card-payment prefixes on French statements; used to keep some brands to direct debits only. */
const NOT_A_CARD_PAYMENT = String.raw`^(?!(CARTE|CB|PAIEMENT PAR CARTE|PAIEMENT CB|ACHAT CB)\b)`;

/**
 * Built-in keyword lexicon (lowest priority). Patterns are matched against the normalized
 * description (upper-case, no accents, "*" treated as a space). Users override any of these
 * with their own or learned rules.
 */
export const SYSTEM_RULES: SystemRule[] = [
  ...contains("Groceries", undefined, [
    "CARREFOUR",
    "LECLERC",
    "AUCHAN",
    "INTERMARCHE",
    "MONOP",
    "FRANPRIX",
    "LIDL",
    "ALDI",
    "CASINO",
    "SUPER U",
    "HYPER U",
    "BIOCOOP",
    "NATURALIA",
    "PICARD",
    "GRAND FRAIS",
    "LA VIE CLAIRE",
    "SPAR",
    "NETTO",
    "G20",
    "COCCINELLE",
    "DAILY MONOP",
    "BIO C BON",
    "LA GRANDE EPICERIE",
  ]),
  ...contains("Dining Out", "DEBIT", [
    "UBER EATS",
    "DELIVEROO",
    "JUST EAT",
    "MCDONALD",
    "BURGER KING",
    "KFC",
    "RESTAURANT",
    "BRASSERIE",
    "PIZZA",
    "PIZZERIA",
    "TRATTORIA",
    "SUSHI",
    "RAMEN",
    "KEBAB",
    "TACOS",
    "O TACOS",
    "BURGER",
    "KITCHEN",
    "FIVE GUYS",
    "DOMINOS",
    "PRET A MANGER",
    "BISTRO",
    "TRAITEUR",
    "CREPERIE",
    "POKE",
    "BAGEL",
    "FRICHTI",
  ]),
  {
    pattern: String.raw`\b(BAR|BARS|PUB|PUBS|BIERE|BIERES|BEER|BEERS|BREWDOG|TAVERNE|TAVERN|COCKTAILS?|SPEAKEASY|GUINGUETTE|TERRASSE|ROOFTOP|LOUNGE|NIGHTCLUB|DISCOTHEQUE|BAR A VIN|BAR A BIERES)\b`,
    category: "Bars & Nightlife",
    direction: "DEBIT",
    matchType: "REGEX",
  },
  ...contains("Coffee & Snacks", "DEBIT", [
    "STARBUCKS",
    "COLUMBUS",
    "COFFEE",
    "MAXICOFFEE",
    "SELECTA",
    "IVS FRANCE",
    "NYX",
    "LAVAZZA",
    "CAFE",
    "CAFETERIA",
    "KB COFFEE",
    "COUTUME",
    "BOULANGERIE",
    "PATISSERIE",
    "BRIOCHE DOREE",
    "MARIE BLACHERE",
    "LA MIE CALINE",
  ]),
  ...contains("Canteen", "DEBIT", [
    "CROUS",
    "IZLY",
    "SODEXO",
    "ELIOR",
    "EUREST",
    "COMPASS GROUP",
    "API RESTAURATION",
    "CANTINE",
    "TURBOSELF",
    "RESTAURATION COLLECTIVE",
  ]),
  { pattern: String.raw`\bRIE\b`, category: "Canteen", direction: "DEBIT", matchType: "REGEX" },
  ...contains("Transport", "DEBIT", [
    "UBER",
    "BOLT",
    "HEETCH",
    "G7",
    "RATP",
    "NAVIGO",
    "TOTALENERGIES",
    "TOTAL ENERGIES",
    "ESSO",
    "SHELL",
    "AVIA",
    "LIME",
    "DOTT",
    "VELIB",
    "INDIGO",
    "SANEF",
    "VINCI AUTOROUTES",
    "APRR",
    "BLABLACAR",
    "GETAROUND",
    "TCL",
    "RTM",
    "TISSEO",
  ]),
  ...contains("Travel", "DEBIT", [
    "AIR FRANCE",
    "EASYJET",
    "RYANAIR",
    "TRANSAVIA",
    "VUELING",
    "BOOKING.COM",
    "BOOKING COM",
    "AIRBNB",
    "HOTEL",
    "EXPEDIA",
    "OUIGO",
    "TRAINLINE",
    "SNCF",
    "EUROSTAR",
    "LUFTHANSA",
    "KLM",
    "FLIXBUS",
  ]),
  ...contains("Utilities", "DEBIT", [
    "EDF",
    "ENGIE",
    "TOTALENERGIES ELEC",
    "VEOLIA",
    "SUEZ",
    "FREE MOBILE",
    "FREE TELECOM",
    "ORANGE",
    "SFR",
    "BOUYGUES",
    "SOSH",
    "RED BY SFR",
    "EKWATEUR",
    "ENERCOOP",
    "PRIXTEL",
    "LEBARA",
    "SYMA",
    "NRJ MOBILE",
    "CORIOLIS",
    "LA POSTE MOBILE",
    "YOUPRICE",
    "AUCHAN TELECOM",
  ]),
  ...contains("Subscriptions", "DEBIT", [
    "NETFLIX",
    "SPOTIFY",
    "DISNEY PLUS",
    "DISNEYPLUS",
    "CANAL+",
    "CANAL PLUS",
    "DEEZER",
    "APPLE.COM/BILL",
    "APPLE COM BILL",
    "APPLE CORK",
    "ICLOUD",
    "GOOGLE STORAGE",
    "GOOGLE ONE",
    "GOOGLE PLAY",
    "YOUTUBE PREMIUM",
    "AMAZON PRIME",
    "PRIME VIDEO",
    "CHATGPT",
    "OPENAI",
    "ANTHROPIC",
    "CLAUDE.AI",
    "MICROSOFT 365",
    "ADOBE",
    "DROPBOX",
    "NOTION",
    "GITHUB",
    "PLAYSTATION",
    "XBOX",
    "NINTENDO",
    "AUDIBLE",
    "MOLOTOV",
    "PARAMOUNT",
    "MAX.COM",
    "DAZN",
    "BEIN",
  ]),
  ...contains("Shopping", "DEBIT", [
    "AMAZON",
    "AMZN",
    "FNAC",
    "DARTY",
    "BOULANGER",
    "ZARA",
    "H&M",
    "UNIQLO",
    "DECATHLON",
    "IKEA",
    "LEROY MERLIN",
    "CASTORAMA",
    "SEPHORA",
    "ZALANDO",
    "VINTED",
    "LEBONCOIN",
    "ALIEXPRESS",
    "SHEIN",
    "TEMU",
    "APPLE STORE",
    "ACTION",
    "KIABI",
    "PRIMARK",
  ]),
  ...contains("Health", "DEBIT", ["PHARMACIE", "PHARMA", "DOCTOLIB", "DENTISTE", "OPTIC", "LABORATOIRE", "MEDECIN", "HOPITAL", "CLINIQUE", "KINE"]),
  ...contains("Entertainment", "DEBIT", [
    "UGC",
    "PATHE",
    "GAUMONT",
    "MK2",
    "FNAC SPECTACLES",
    "TICKETMASTER",
    "STEAM",
    "EPIC GAMES",
    "SHOTGUN",
    "DICE.FM",
    "HIPPODROME",
    "BILLETREDUC",
  ]),
  ...contains("Personal Care", "DEBIT", [
    "BASIC FIT",
    "BASIC-FIT",
    "FITNESS PARK",
    "NEONESS",
    "CLUB MED GYM",
    "COIFF",
    "BARBER",
    "YVES ROCHER",
    "NOCIBE",
    "MARIONNAUD",
  ]),
  // Generic insurance words anywhere; insurer brands only when it isn't a card payment, so a card
  // payment at an employer that happens to be an insurer (e.g. its canteen) isn't filed as insurance.
  ...contains("Insurance", "DEBIT", ["ASSURANCE", "MUTUELLE"]),
  {
    pattern: `${NOT_A_CARD_PAYMENT}.*\\b(AXA|MAIF|MACIF|MAAF|MATMUT|ALLIANZ|GROUPAMA|PACIFICA|GMF|LUKO|ALAN|GENERALI|SWISSLIFE|HISCOX|LEOCARE|HEYME|LMDE)\\b`,
    category: "Insurance",
    direction: "DEBIT",
    matchType: "REGEX",
  },
  ...contains("Taxes", "DEBIT", ["DGFIP", "IMPOT", "TRESOR PUBLIC", "FINANCES PUBLIQUES", "URSSAF", "ANTS"]),
  ...contains("Fees & Charges", "DEBIT", ["COTIS", "FRAIS", "COMMISSION", "AGIOS", "OFFRE GLOBULE", "OFFRE ESSENTIEL", "FEE", "INTERETS DEBITEURS"]),
  ...contains("Cash", "DEBIT", ["RETRAIT DAB", "RETRAIT GAB", "RETRAIT", "CASH WITHDRAWAL", "CASH AT", "ATM"]),
  ...contains("Housing", "DEBIT", ["LOYER", "FONCIA", "NEXITY", "ORPI", "SYNDIC", "CITYA", "ECHEANCE PRET", "PRET IMMO"]),
  ...contains("Pets", "DEBIT", ["VETERINAIRE", "VETO", "MAXI ZOO", "ANIMALIS", "TRUFFAUT"]),
  ...contains("Gifts & Donations", "DEBIT", ["UNICEF", "CROIX ROUGE", "MSF", "RESTOS DU COEUR", "LEETCHI", "LYDIA CAGNOTTE"]),
  ...contains("Salary", "CREDIT", ["SALAIRE", "PAYROLL", "SALARY", "REMUNERATION"]),
  // "PAIE0426"-style payroll references; \b keeps it away from "PAIEMENT".
  { pattern: String.raw`PAIE\d{4}\b|\bPAIE\b`, category: "Salary", direction: "CREDIT", matchType: "REGEX" },
  ...contains("Refunds", "CREDIT", ["REMBOURSEMENT", "REFUND", "AVOIR", "CPAM", "AMELI"]),
  ...contains("Investment Income", "CREDIT", ["INTERETS", "INTEREST", "DIVIDEND", "COUPON"]),
  ...contains(TRANSFER_CATEGORY, undefined, [
    "TOP-UP",
    "TOP UP",
    "TOPUP",
    "EXCHANGED TO",
    "EXCHANGE TO",
    "TO EUR",
    "FROM EUR",
    "VIREMENT INTERNE",
    "VIR INTERNE",
    "APPLE PAY TOP",
    "POCKET",
    "VAULT",
    "REVOLUT",
  ]),
  ...contains("Savings & Investments", undefined, [
    "LIVRET A",
    "LDDS",
    "ASSURANCE VIE",
    "BOURSORAMA BANQUE",
    "TRADE REPUBLIC",
    "DEGIRO",
    "BOURSE DIRECT",
    "COINBASE",
    "BINANCE",
    "KRAKEN",
    "YOMONI",
    "NALO",
    "SAVINGS",
    "EPARGNE",
  ]),
];

/** Default priority per source; learned corrections must beat everything else. */
export const PRIORITY = { LEARNED: 1000, USER: 500, AI: 200, SYSTEM: 100 } as const;
