import {
  Archive,
  ArrowLeftRight,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  Camera,
  Car,
  CircleDashed,
  Clapperboard,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Croissant,
  CupSoda,
  Dumbbell,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  Handshake,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Martini,
  Mountain,
  Music,
  Palette,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Receipt,
  Repeat,
  Salad,
  Sandwich,
  School,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Soup,
  Sparkles,
  Stethoscope,
  Tag,
  Tent,
  Ticket,
  TrainFront,
  TramFront,
  TrendingUp,
  Trophy,
  Undo2,
  Users,
  UtensilsCrossed,
  Wallet,
  Waves,
  Wifi,
  Wine,
  type LucideIcon,
} from "lucide-react";
import { colorOf } from "@/lib/palette";
import { cn } from "@/lib/utils";

/** Icons offered for categories, in the order shown by the icon picker. */
export const ICONS: Record<string, LucideIcon> = {
  Tag,
  ShoppingBasket,
  ShoppingCart,
  UtensilsCrossed,
  Pizza,
  Sandwich,
  Salad,
  Soup,
  Coffee,
  Croissant,
  Cookie,
  CupSoda,
  Beer,
  Wine,
  Martini,
  PartyPopper,
  TramFront,
  TrainFront,
  Bus,
  Bike,
  Car,
  Fuel,
  Plane,
  Tent,
  Mountain,
  Waves,
  House,
  Sofa,
  Hammer,
  Plug,
  Wifi,
  Smartphone,
  Laptop,
  Repeat,
  ShoppingBag,
  Shirt,
  Scissors,
  Sparkles,
  Dumbbell,
  Trophy,
  HeartPulse,
  Pill,
  Stethoscope,
  Ticket,
  Clapperboard,
  Popcorn,
  Music,
  Gamepad2,
  Camera,
  Palette,
  BookOpen,
  GraduationCap,
  School,
  Baby,
  PawPrint,
  Users,
  Handshake,
  Gift,
  ShieldCheck,
  Landmark,
  Receipt,
  CreditCard,
  Banknote,
  Wallet,
  Coins,
  PiggyBank,
  TrendingUp,
  BriefcaseBusiness,
  Undo2,
  ArrowLeftRight,
  Flame,
  Archive,
  CircleDashed,
};

export function CategoryIcon({ icon, color, size = "md", className }: { icon: string; color: string; size?: "sm" | "md" | "lg"; className?: string }) {
  const Icon = ICONS[icon] ?? Tag;
  const c = colorOf(color);
  const dims =
    size === "sm" ? "size-6 rounded-lg [&_svg]:size-3.5" : size === "lg" ? "size-10 rounded-xl [&_svg]:size-5" : "size-8 rounded-[10px] [&_svg]:size-4";
  return (
    <span
      className={cn("inline-flex shrink-0 items-center justify-center", dims, className)}
      style={{ background: `color-mix(in srgb, ${c} 18%, transparent)`, color: c }}
    >
      <Icon strokeWidth={2} />
    </span>
  );
}

export function CategoryDot({ color, className }: { color: string; className?: string }) {
  return <span className={cn("inline-block size-2 shrink-0 rounded-full", className)} style={{ background: colorOf(color) }} />;
}
